name: Laravel Test

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer update

    - name: Copy sample env file
      run: cp .env.example .env

    - name: Install App key 2
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test --coverage-html test-results
      env:
        XDEBUG_MODE: coverage

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results

  push_to_gh_pages:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: gh_pages

    - name: Set up Git
      run: |
        git config user.name "ramanjar"
        git config user.email "ramanjar@unal.edu.co"

    - name: Download Code Coverage Report
      uses: actions/download-artifact@v2
      with:
        name: test-results
        path: test-results

    - name: Merge Changes into gh-pages Branch
      run: |
        git add .
        git commit -m "Updated test results"
        git push https://$ACTIONS_TOKEN@github.com/ramanjar/actions gh_pages
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
