name: Laravel Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer update

    - name: Copy sample env file
      run: cp .env.example .env

    - name: Install App key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test
